### ISSUE TITLE
Empty Object Showing in Member Call

### ISSUE THREAD

**Issue by EvanPiro** [LibraryOfCongress/api.congress.gov#125] opened 2023-07-27 17:42 UTC
I'm getting an empty object in the list of member objects after making the member call. This is making decoding responses fail on my end. I've implemented a workaround but was wondering if this is something that can be fixed on the server side.

Url: `https://api.congress.gov/v3/member`

Response:
```
[
...
        {},
        {
            "bioguideId": "E000071",
            "depiction": {
                "attribution": "Image courtesy of the Member",
                "imageUrl": "https://www.congress.gov/img/member/e000071_200.jpg"
            },
            "district": 6,
            "name": "Ellzey, Jake",
            "partyName": "Republican",
            "state": "Texas",
            "terms": {
                "item": [
                    {
                        "chamber": "House of Representatives",
                        "startYear": 2021
                    }
                ]
            },
            "updateDate": "2023-06-27T20:12:36Z",
            "url": "https://api.congress.gov/v3/member/E000071?format=json"
        },
...
```

**Comment by mnewatloc** [comment] 2023-07-28 19:21
We have been unable to replicate this issue. Can you try again and let us know if it's still a problem?

**Comment by ryparker** [comment] 2023-07-28 21:37
Duplicate of https://github.com/LibraryOfCongress/api.congress.gov/issues/120

**Comment by mnewatloc** [comment] 2023-08-03 18:20
We've created a ticket for this issue. Thank you for bringing it to our attention.

**Comment by EvanPiro** [comment] 2023-08-04 15:16
Is the API data indexing service open-source? I'd love to help identify/fix this issue as I'm running a service that currently relies on this data.

**Closed** 2023-08-16 15:59 UTC
Labels: bug, duplicate
